### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by fab-gentile** [cschreib/slinefit#2]
Hi,

I'm trying to install slinefit, but I get this error message:

[ 75%] Performing build step for 'slinefit'
[ 50%] Building CXX object CMakeFiles/slinefit.dir/slinefit.cpp.o
In file included from /home/fabrizio/slinefit/external/include/vif/core/vec.hpp:1236,
                 from /home/fabrizio/slinefit/external/include/vif.hpp:2,
                 from /home/fabrizio/slinefit/src/slinefit.cpp:1:
/home/fabrizio/slinefit/external/include/vif/core/bits/operators.hpp:159:15: error: invalid use of incomplete type ‘struct vif::impl::op_add_t’
  159 |     VECTORIZE(+, +=)
      |                              ^
/home/fabrizio/slinefit/external/include/vif/core/bits/operators.hpp:81:56: error: template argument 1 is invalid
   81 |         vec<Dim,typename impl::op_res_t<OP_TYPE(op),T,U>::type> operator op (const vec<Dim,T>& v, const vec<Dim,U>& u) { \
      | 
/home/fabrizio/slinefit/external/include/vif/core/bits/operators.hpp:81:63: error: template argument 2 is invalid
   81 |         vec<Dim,typename impl::op_res_t<OP_TYPE(op),T,U>::type> operator op (const vec<Dim,T>& v, const vec<Dim,U>& u) { \
      |                                                                                            ^
/home/fabrizio/slinefit/external/include/vif/core/bits/operators.hpp:159:15: error: invalid use of incomplete type ‘struct vif::impl::op_add_t’
  159 |     VECTORIZE(+, +=)
      |                              ^
compilation terminated due to -fmax-errors=5.

Any suggestion on how to fix it??

Thank you,
Fabrizio

**Comment by cschreib** [comment]
Hi Fabrizio, and sorry for the long response time. The notification slipped through my inbox. Your issue is similar to https://github.com/cschreib/fastpp/issues/16, so the fix should be the same.

I committed a fix to the repo. If you are able to try the latest commit on the master branch, the problem should be fixed. Please let me know if that worked!

**Comment by fab-gentile** [comment]
Yes! Now it's working! Thank you!
