### ISSUE TITLE
Getting error while running "make install"

### ISSUE THREAD

**Issue by squai** [cschreib/slinefit#3]
Hi Corentin,

I'm trying to install Slinefit on my mac, but I get the same error as in the following issue regarding Fastpp: https://github.com/cschreib/fastpp/issues/14

------------
ERROR:
/Users/salvatore/Documents/programs/slinefit/external/cfitsio/group.c:5476:3: error: call to undeclared function 'getcwd'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  getcwd(buff,FLEN_FILENAME);
  ^
1 error generated.
make[5]: *** [CMakeFiles/cfitsio.dir/group.c.o] Error 1
make[4]: *** [CMakeFiles/cfitsio.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [cfitsio-prefix/src/cfitsio-stamp/cfitsio-build] Error 2
make[1]: *** [CMakeFiles/cfitsio.dir/all] Error 2
make: *** [all] Error 2
------------

May I ask you if you could fix the master for Slinefit as well? 

Thank you so much,

Salvatore

**Comment by cschreib** [comment]
Hi Salvatore. I pushed a fix to the `master` branch; can you pull the latest commit and try again, then let me know if it fixed the problem for you? Thank you for reporting this.

**Comment by squai** [comment]
Yeah! Thanks a lot (also for the quick help!).

Cheers,
Salvatore

**Comment by cschreib** [comment]
Cheers; I'll close this issue then.
