### ISSUE TITLE
Fits file I/O issue when lines are not used

### ISSUE THREAD

**Issue by themiyan** [cschreib/slinefit#7]
There is a something missing when the `*slfit.fits` is written to disk if no lines are mentioned in the line fitting process. This leads to astropy not being able to read the output file. 

I think this is because `dtype` is missing in some of the tables?

```
> /Users/wnanayakkara/opt/anaconda3/envs/jwst/lib/python3.10/site-packages/astropy/io/fits/column.py(1730)dtype()
   1728                 # as they are always of shape (2,)
   1729                 if format_.format == "A":
-> 1730                     dt = np.dtype((dt.char + str(dim[-1]), dim[:-1]))
   1731                 else:
   1732                     dt = np.dtype((dt.base, dim))



ipdb>  for format_, dim, cols in zip(self.formats, self._dims, self.columns): print(cols); np.dtype((dt.char + str(dim[-1]), dim[:-1]))
name = 'CHI2'; format = '1D'
*** TypeError: 'NoneType' object is not subscriptable

```

![Screenshot 2023-10-09 at 12 05 41](https://github.com/cschreib/slinefit/assets/5274688/6222296f-1df5-4b48-97d1-e7b839959fea)

**Comment by cschreib** [comment]
Looks like astropy doesn't like empty strings in tables. I've pushed a workaround which seems to help, can you try again with ac4b1126de779acb3c1cbdf0d774000a5c98b7e9 please? This should still give you a warning, but at least it will return the data.

**Comment by themiyan** [comment]
Thanks. I do get the warnings but also end up with a TypeError

![Screenshot 2023-10-10 at 10 25 29](https://github.com/cschreib/slinefit/assets/5274688/73a167a8-0e9a-41ee-9b60-376b4699bef3)

Basically 

```
> /Users/wnanayakkara/opt/anaconda3/envs/jwst/lib/python3.10/site-packages/astropy/io/fits/connect.py(281)read_table_fits()
    279             masked = True
    280         elif mask_invalid and issubclass(coltype, np.inexact):
--> 281             mask = np.isnan(data[col.name])
    282         elif mask_invalid and issubclass(coltype, np.character):
    283             mask = col.array == b""

ipdb>  data[col.name]
array([], dtype='|V8')

```

`np.isnan` can take empty arrays but the dtype `V8` seems to be the issue. I don't think I've seen that type before?

**Comment by cschreib** [comment]
Looks like this means "void" (i.e., unknown type). Again, astropy seems to be confused by an empty column. The FITS tables created by `slinefit` are column-oriented table, and I don't think `Table` is able to understand that very well (it is meant for row-oriented tables, i.e., traditional tables with multiple rows and simple column types).

I would recommend you use the [`pycolfits`](https://github.com/cschreib/vif/blob/master/python/pycolfits.py) package I created a while back (it's not in `pip`, you have to download it and install manually...). This is able to read the file correctly. Here's some docs:
![image](https://github.com/cschreib/slinefit/assets/2236577/684c0d65-2abd-4d19-be5d-5456e65cfe3c)

Sorry for the poor user experience! The right thing to do would be to report these issues, with the example files, to the astropy people, and have them improve their code. I don't really have it in me though :)

NB: an alternative, if you're struggling with FITS tables, is to set the `ascii` flag when calling `slinefit`. This will output traditional ASCII tables in addition to the FITS tables. This won't contain everything though, only the list of lines (and their properties) and the P(z). Not the best-fit redshift or its error bar.

**Comment by themiyan** [comment]
Great, thanks Corentin!. Yes I'll try using the `pycolfits` and see for things we don't have clear lines. Most of the same do have lines and some may have very weak limits so useful to add lines most of the time as long as the no line z is similar to the one with the line to extract limits.
