### ISSUE TITLE
Poor continuum with line + continuum sources with lsf

### ISSUE THREAD

**Issue by themiyan** [cschreib/slinefit#8]
Hi Corentin,

When spectra with strong emission lines are fit using the `lsf` option, there seems to be an issue with the fine,l fit accuracy. 

Example 1:
Without lsf
<img width="833" alt="Screenshot 2023-11-15 at 14 25 13" src="https://github.com/cschreib/slinefit/assets/5274688/dea9c88b-7a3c-4050-919b-2d6312526e71">

With lsf
<img width="913" alt="Screenshot 2023-11-15 at 14 25 25" src="https://github.com/cschreib/slinefit/assets/5274688/c5c00099-8264-4be5-9e01-d88658fdb2dd">

Example 2:
without lsf
![Screenshot 2023-11-15 at 14 26 30](https://github.com/cschreib/slinefit/assets/5274688/e2925f29-ab82-4381-8e85-116fa76d39f4)

with lsf:
<img width="828" alt="Screenshot 2023-11-15 at 14 27 06" src="https://github.com/cschreib/slinefit/assets/5274688/31ae07fb-f446-4300-8af3-c4a51551bea0">

This is likely driven by the extra broadening of the templates when lsf is introduced. So lines + continuum doesn't really produce an accurate match. 

The 2 inputs are here in case you wanna check https://www.dropbox.com/t/g1sAOmpjaiafvIXU

**Comment by cschreib** [comment]
Hi Themiya, and thanks for reporting this issue. Can you please share the `slinefit` command line options you used to generate these various plots? I am struggling to reproduce exactly what you are getting.

**Comment by themiyan** [comment]
Oh no, maybe I'm doing something wrong then:

I do something like this, for example and with and without `lsf_hdu=5`

```/data/themiya/softwares/slinefit/bin/slinefit onedspec_obs100_02076_for_slinefit.fits z0=3.8 dz=.2 delta_z=0.1 num_mc=200 threads=32 width_min=5000 width_max=50000 delta_width=0.25 use_global_chi2 full_range verbose lines=[em_halpha,em_o3_5007,em_n2_6583] fit_continuum_template template_dir=/data/themiya/softwares/slinefit/bin/templates/  save_model lsf_hdu=5```

**Comment by cschreib** [comment]
Just checking, did you really mean `width_min=5000 width_max=50000` (i.e., 5000 km/s to 50000 km/s)?

**Comment by themiyan** [comment]
sorry, I normally allow from ~500 km/s onwards, was doing some testing and copied the wrong one over. To be extra careful I did it again now as follows: 
`/data/themiya/softwares/slinefit/bin/slinefit onedspec_obs100_02076_for_slinefit.fits z0=3.8 dz=.2 delta_z=0.1 num_mc=200 threads=32 width_min=500 width_max=7000 delta_width=0.25 use_global_chi2 full_range verbose lines=[em_halpha,em_o3_5007,em_n2_6583] fit_continuum_template template_dir=/data/themiya/softwares/slinefit/bin/templates/  save_model lsf_hdu=5`

With LSF 
![Screenshot 2023-11-16 at 09 22 54](https://github.com/cschreib/slinefit/assets/5274688/3254b3c6-bf18-4b41-b17c-4ad16f70ba85)


without LSF

![Screenshot 2023-11-16 at 09 20 27](https://github.com/cschreib/slinefit/assets/5274688/23770ed0-c387-4a6f-ae39-1cee11ac36aa)


For the lines `[b'em_o3_5007-2', b'em_o3_5007-1', b'em_n2_6583-2', b'em_halpha   ',
       b'em_n2_6583-1']`
line WIDTH's are
With LSF: `[1312.5 , 1312.5  , 1041.66666667, 7000.,1041.66666667]`
       
Without LSF:`[1312.5 , 1312.5   ,  500.  , 3208.33333333, 500.  ]`

Clearly 500km/s is too small to be resolved. With LSF it's accounting for this correctly I think, but as you see the fit is problematic due to the strong abs lines.

**Comment by themiyan** [comment]
Also all the fluxes and EWs are negative when fitting with LSF in this case and +ve without LSF. 

For example see here: https://www.dropbox.com/t/HD3j19h2Co1OyTPN

This seems a bit weird because even if the abs lines are broadened due to the effects of the LSF, to obtain the fit the emission line EW may need to be stronger than without the LSF.

**Comment by cschreib** [comment]
Thanks, I get the same results as you now. There is something wrong with the line profiles; they are all detected as emission lines, but something is creating negative "wings":
![image](https://github.com/cschreib/slinefit/assets/2236577/5a6ec0bc-13c5-4880-92bf-ed1eb7a00c6e)

I must have made a mistake in the line integration code when accounting for the LSF. I'll investigate.

**Comment by cschreib** [comment]
That was indeed the problem. Fixed it, and it's much better now:
![image](https://github.com/cschreib/slinefit/assets/2236577/4c65f4cd-f264-40d9-9e2c-c0a5bfaf162d)

Sorry for the trouble; to make up for the time you lost, I included a decent performance optimisation as well (36s -> 22s on my machine, with MC sims disabled). Try the latest commit on master, and let me know if that solves all your issues.

**Comment by cschreib** [comment]
Hmm I'll do another set of tests to check that the fluxes are correct, hold on.

**Comment by cschreib** [comment]
Yes, looks good!

**Comment by themiyan** [comment]
Awesome, thanks Corentin. The fits looks way better now! The update halved the time in the machine here, 55s to 27s with mcmc!

**Comment by karlglazebrook** [comment]
Corentin you are amazing. See you next year! When are you coming?

**Comment by cschreib** [comment]
I don't know! Nothing actually planned yet. I'll let you know if and when that happens ;)
